### ISSUE TITLE
Tiling artifacts exist on 1m DEM roughly every 60m

### ISSUE THREAD

**Issue by brentwilder** [hyriver/py3dep#57]
# **What happened**:  
My team and I used `.get_map()` function (see below) to generate 1 meter DEM for our study site. On first glance the DEM looked perfectly fine. However, when we differenced this grid with our own DEM grid with snow, we found there were edge/tiling artifacts from the 3DEP product. At first I believed this to be our own snow DEM. However, after extensive testing I was able to narrow it down to being from the USGS DEM. Finally, I tried it with 1 meter DEM straight from https://apps.nationalmap.gov/downloader/ , __and there were no artifacts__. Meaning that there were ~60m tiling artifacts present as a result of me misusing py3dep (very possible), or something off in the way py3dep is calling the 1m 3DEP dataset.

```python
def download_dem(las_fp, dem_fp = 'dem.tif'):
    """
    Reads the crs and bounds of a las file and downloads a DEM from py3dep
    Must be in the CONUS.
    Parameters:
    las_fp (str): filepath to las file to get bounds and crs
    dem_fp (str) [optional]: filepath to save DEM at. [default = './dem.tif']
    Returns:
    crs (pyproj CRS): CRS object from las header
    project (shapely transform): shapely transform used in conversion
    """
    # read crs of las file
    with laspy.open(las_fp) as las:
        hdr = las.header
        crs = hdr.parse_crs()
    log.debug(f"CRS used is {crs}")
    # create transform from wgs84 to las crs
    wgs84 = pyproj.CRS('EPSG:4326')
    project = pyproj.Transformer.from_crs(crs, wgs84 , always_xy=True).transform
    # calculate bounds of las file in wgs84
    utm_bounds = box(hdr.mins[0], hdr.mins[1], hdr.maxs[0], hdr.maxs[1])
    wgs84_bounds = transform(project, utm_bounds)
    # download dem inside bounds
    dem_wgs = py3dep.get_map('DEM', wgs84_bounds, resolution = 1, crs = 'epsg:4326')
    log.debug(f"DEM bounds: {dem_wgs.rio.bounds()}. Size: {dem_wgs.size}")
    # reproject to las crs and save
    dem_utm = dem_wgs.rio.reproject(crs)
    dem_utm.rio.to_raster(dem_fp)
    log.debug(f"Saved to {dem_fp}")
    return dem_fp, crs, project

```

# **Environment**:
OS: Ubuntu 20.04.4 LTS x86_64

py3dep version: 0.13.3

Conda environemnt via .yaml below
```yaml
name: iceroad
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - python-pdal
  - gdal
  - rioxarray
  - py3dep
  - shapely
  - docopt
  - pip
  - pip:
    - whitebox
    - matplotlib
    - geopandas
    - rasterio
    - xarray
    - pandas
    - laspy[lazrs,laszip]
```

## Difference of DEMs with py3dep

![bad](https://user-images.githubusercontent.com/56372982/180662232-3a74e357-d114-4c0a-a4da-ba1e3169eadc.png)

## Difference of DEMs with https://apps.nationalmap.gov/downloader/

![clean](https://user-images.githubusercontent.com/56372982/180662234-2b3c9f33-14ad-46f1-a704-c39812d67dde.png)
